apiVersion: csi.aliyun.com/v1alpha1
kind: NodeLocalStorageInitConfig
metadata:
  name: {{ .Values.name }}
spec:
# globalConfig为全局默认节点配置，
# 在agent初始化创建NodeLocalStorage资源时会填充到其Spec中
  globalConfig:
#   listConfig为存储设备的白黑名单，支持正则表达式
    listConfig:
      vgs:
        include:
        - {{ .Values.name }}-pool-[0-9]+
      mountPoints:
        include:
        - /mnt/open-local/disk-[0-9]+
    resourceToBeInited:
      vgs:
      - devices:
        - /dev/sdb
        name: {{ .Values.name }}-pool-0