apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotClass
metadata:
  name: {{ .Values.storageclass.lvm.name }}
driver: {{ .Values.driver }}
deletionPolicy: Delete
parameters:
  csi.alibaba.com/readonly: "true"
  csi.alibaba.com/snapshot-initial-size: 4Gi
  csi.alibaba.com/snapshot-expansion-size: 1Gi
  csi.alibaba.com/snapshot-expansion-threshold: 50%