name: open-local
namespace: kube-system
driver: local.csi.aliyun.com
images:
  local:
    image: thebeatles1994/open-local
    tag: v0.2.3-dev
  registrar:
    image: k8s.gcr.io/sig-storage/csi-node-driver-registrar
    tag: v2.3.0
  provisioner:
    image: k8s.gcr.io/sig-storage/csi-provisioner
    tag: v2.2.2
  resizer:
    image: k8s.gcr.io/sig-storage/csi-resizer
    tag: v1.3.0
  snapshotter:
    image: k8s.gcr.io/sig-storage/csi-snapshotter
    tag: v3.0.3
  snapshot_controller:
    image: k8s.gcr.io/sig-storage/snapshot-controller
    tag: v3.0.3
agent:
  name: open-local-agent
  # This block device will be used to create as a Volume Group in every node
  # Open-Local does nothing if the device has been formatted or mountted
  device: /dev/vdb
extender:
  name: open-local-scheduler-extender
  # scheduling strategy: binpack/spread
  strategy: binpack
  # scheduler extender http port
  port: 23000
storageclass:
  lvm:
    name: open-local-lvm
  device_ssd:
    name: open-local-device-ssd
  device_hdd:
    name: open-local-device-hdd
  mountpoint_ssd:
    name: open-local-mountpoint-ssd
  mountpoint_hdd:
    name: open-local-mountpoint-hdd